# Generated by Django 5.2.7 on 2025-11-10 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0015_alter_order_status_orderpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute/image/'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute_group/image/'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute/image/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/files/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/quotation/files/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/payment/files/'),
        ),
    ]
